- hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: Create task definition
      ecs_taskdefinition:
      containers:
      - name: simple-app
        cpu: 1
        essential: true
        image: "{{ image_name }}"
        memory: 300
        portMappings:
        - containerPort: 80
          hostPort: 80
        family: test-cluster-taskdef
        state: present
  register: task_output
    - name: Create Service 
      ecs_service:
      state: present
      name: console-test-service
      cluster: new_cluster
      task_definition: new_cluster-task:1"
      desired_count: 3
      deployment_configuration:
        minimum_healthy_percent: 75
        maximum_percent: 150
